namespace Nightfall.Net.Models
{
    public enum ConfidenceEnum
    {
        VERY_UNLIKELY,
        UNLIKELY,
        POSSIBLE,
        LIKELY,
        VERY_LIKELY
    }

    public enum MatchType
    {
        PARTIAL,
        FULL
    }

    public enum LogicalOperation
    {
        ANY,
        ALL
    }

    public enum DetectorType
    {
        NIGHTFALL_DETECTOR,
        REGEX,
        WORD_LIST
    }

    public enum DetectorGlossary
    {
        CANADA_BANK_ACCOUNT,
        CANADA_BC_PHN,
        CANADA_DRIVERS_LICENSE_NUMBER,
        CANADA_GOVERNMENT_ID,
        CANADA_OHIP,
        CANADA_PASSPORT,
        CANADA_PERMANENT_RESIDENT_NUMBER,
        CANADA_QUEBEC_HIN,
        CANADA_SOCIAL_INSURANCE_NUMBER,
        DATE,
        DATE_OF_BIRTH,
        EMAIL_ADDRESS,
        FRANCE_CNI,
        FRANCE_INSEE,
        FRANCE_PASSPORT,
        GERMANY_IDENTITY_NUMBER,
        GERMANY_PASSPORT,
        IRELAND_PASSPORT,
        IRELAND_PPSN,
        LOCATION,
        PERSON_NAME,
        PHONE_NUMBER,
        SCOTLAND_COMMUNITY_HEALTH_INDEX_NUMBER,
        UK_DRIVERS_LICENSE_NUMBER,
        UK_ELECTORAL_ROLL_NUMBER,
        UK_NATIONAL_HEALTH_SERVICE_NUMBER,
        UK_NATIONAL_INSURANCE_NUMBER,
        UK_PASSPORT,
        UK_TAXPAYER_REFERENCE,
        US_DRIVERS_LICENSE_NUMBER,
        US_INDIVIDUAL_TAXPAYER_IDENTIFICATION_NUMBER,
        US_PASSPORT,
        US_SOCIAL_SECURITY_NUMBER,
        US_VEHICLE_IDENTIFICATION_NUMBER,
        AMERICAN_BANKERS_CUSIP_ID,
        CREDIT_CARD_NUMBER,
        IBAN_CODE,
        SWIFT_CODE,
        US_BANK_ROUTING_MICR,
        US_EMPLOYER_IDENTIFICATION_NUMBER,
        FDA_NATIONAL_DRUG_NAME,
        ICD10_CODE,
        ICD10_DIAGNOSIS_DESCRIPTION,
        ICD9_CODE,
        ICD9_DIAGNOSIS_DESCRIPTION,
        US_HEALTH_INSURANCE_CLAIM_NUMBER,
        US_HEALTHCARE_NPI,
        US_MEDICARE_BENEFICIARY_IDENTIFIER,
        IMEI_HARDWARE_ID,
        IP_ADDRESS,
        MAC_ADDRESS,
        API_KEY,
        CRYPTOGRAPHIC_KEY,
        DATABASE_CONNECTION_STRING,
        GCP_CREDENTIALS,
        PASSWORD_IN_CODE
    }
}